<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TownSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('towns')->insert([

            // Bocas del Toro

            ['state_id' => '1', 'city_id' => '1', 'name' => 'Almirante'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Bajo Culubre'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Barriada Guaymí'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Barrio Francés'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Cauchero'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Ceiba'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Miraflores'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Nance de Riscó'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Valle de Aguas Arriba'],
            ['state_id' => '1', 'city_id' => '1', 'name' => 'Valle de Riscó'],

            ['state_id' => '1', 'city_id' => '2', 'name' => 'Bocas del Toro'],
            ['state_id' => '1', 'city_id' => '2', 'name' => 'Bastimentos'],
            ['state_id' => '1', 'city_id' => '2', 'name' => 'Boca del Drago'],
            ['state_id' => '1', 'city_id' => '2', 'name' => 'Punta Laurel'],
            ['state_id' => '1', 'city_id' => '2', 'name' => 'San Cristóbal'],
            ['state_id' => '1', 'city_id' => '2', 'name' => 'Tierra Oscura'],

            ['state_id' => '1', 'city_id' => '3', 'name' => 'Barranco Adentro'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Barriada 4 de Abril'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Changuinola'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Cochigro'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'El Empalme'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'El Silencio'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Finca 4'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Finca 6'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Finca 12'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Finca 30'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Finca 51'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Finca 60'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Finca 66'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Guabito'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'La Gloria,'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'La Mesa'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Las Delicias'],
            ['state_id' => '1', 'city_id' => '3', 'name' => 'Las Tablas'],

            ['state_id' => '1', 'city_id' => '4', 'name' => 'Bajo Cedro'],
            ['state_id' => '1', 'city_id' => '4', 'name' => 'Chiriquí Grande'],
            ['state_id' => '1', 'city_id' => '4', 'name' => 'Miramar'],
            ['state_id' => '1', 'city_id' => '4', 'name' => 'Punta Peña'],
            ['state_id' => '1', 'city_id' => '4', 'name' => 'Punta Robalo'],
            ['state_id' => '1', 'city_id' => '4', 'name' => 'Rambala'],

            // Coclé

            ['state_id' => '2', 'city_id' => '5', 'name' => 'Aguadulce'],
            ['state_id' => '2', 'city_id' => '5', 'name' => 'Barrios Unidos'],
            ['state_id' => '2', 'city_id' => '5', 'name' => 'El Cristo'],
            ['state_id' => '2', 'city_id' => '5', 'name' => 'El Hato de San Juan de Dios'],
            ['state_id' => '2', 'city_id' => '5', 'name' => 'El Roble'],
            ['state_id' => '2', 'city_id' => '5', 'name' => 'Pocrí'],
            ['state_id' => '2', 'city_id' => '5', 'name' => 'Pueblos Unidos'],
            ['state_id' => '2', 'city_id' => '5', 'name' => 'Virgen del Carmen'],

            ['state_id' => '2', 'city_id' => '6', 'name' => 'Antón'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'Caballero'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'Cabuya'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'El Chirú'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'El Retiro'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'El Valle'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'Juan Díaz'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'Río Hato'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'San Juan de Dios'],
            ['state_id' => '2', 'city_id' => '6', 'name' => 'Santa Rita'],

            ['state_id' => '2', 'city_id' => '7', 'name' => 'El Harino'],
            ['state_id' => '2', 'city_id' => '7', 'name' => 'El Potrero'],
            ['state_id' => '2', 'city_id' => '7', 'name' => 'La Pintada'],
            ['state_id' => '2', 'city_id' => '7', 'name' => 'Las Lomas'],
            ['state_id' => '2', 'city_id' => '7', 'name' => 'Llano Grande'],
            ['state_id' => '2', 'city_id' => '7', 'name' => 'Llano Norte'],
            ['state_id' => '2', 'city_id' => '7', 'name' => 'Piedras Gordas'],

            ['state_id' => '2', 'city_id' => '8', 'name' => 'Capellanía'],
            ['state_id' => '2', 'city_id' => '8', 'name' => 'El Caño'],
            ['state_id' => '2', 'city_id' => '8', 'name' => 'Guzmán'],
            ['state_id' => '2', 'city_id' => '8', 'name' => 'Las Huacas'],
            ['state_id' => '2', 'city_id' => '8', 'name' => 'Natá de los Caballeros'],
            ['state_id' => '2', 'city_id' => '8', 'name' => 'Toza'],
            ['state_id' => '2', 'city_id' => '8', 'name' => 'Villarreal'],

            ['state_id' => '2', 'city_id' => '9', 'name' => 'El Copé'],
            ['state_id' => '2', 'city_id' => '9', 'name' => 'El Palmar'],
            ['state_id' => '2', 'city_id' => '9', 'name' => 'El Picacho'],
            ['state_id' => '2', 'city_id' => '9', 'name' => 'La Pava'],
            ['state_id' => '2', 'city_id' => '9', 'name' => 'Olá'],

            ['state_id' => '2', 'city_id' => '10', 'name' => 'Boca de Tucué'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Candelario Ovalle'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Cañaveral'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Chiguirí Arriba'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Coclé'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'El Coco'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Las Minas'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Pajonal'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Penonomé'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Riecito'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Río Grande'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Río Indio'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'San Miguel'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Toabré'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Tulú'],
            ['state_id' => '2', 'city_id' => '10', 'name' => 'Victoriano Lorenzo'],

            // Colón

            ['state_id' => '3', 'city_id' => '11', 'name' => 'Achiote'],
            ['state_id' => '3', 'city_id' => '11', 'name' => 'El Guabo'],
            ['state_id' => '3', 'city_id' => '11', 'name' => 'La Encantada'],
            ['state_id' => '3', 'city_id' => '11', 'name' => 'Nuevo Chagres'],
            ['state_id' => '3', 'city_id' => '11', 'name' => 'Palmas Bellas'],
            ['state_id' => '3', 'city_id' => '11', 'name' => 'Piña'],
            ['state_id' => '3', 'city_id' => '11', 'name' => 'Salud'],

            ['state_id' => '3', 'city_id' => '12', 'name' => 'Barrio Norte'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Barrio Sur'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Buena Vista'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Cativá'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Ciricito'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Cristóbal'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Cristóbal Este'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Escobal'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Limón'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Nueva Providencia'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Puerto Pilón'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Sabanitas'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Salamanca'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'San Juan'],
            ['state_id' => '3', 'city_id' => '12', 'name' => 'Santa Rosa'],

            ['state_id' => '3', 'city_id' => '13', 'name' => 'Coclé del Norte'],
            ['state_id' => '3', 'city_id' => '13', 'name' => 'El Guásimo'],
            ['state_id' => '3', 'city_id' => '13', 'name' => 'Gobea'],
            ['state_id' => '3', 'city_id' => '13', 'name' => 'Miguel de la Borda'],
            ['state_id' => '3', 'city_id' => '13', 'name' => 'Río Indio'],

            ['state_id' => '3', 'city_id' => '14', 'name' => 'Nueva Esperanza'],
            ['state_id' => '3', 'city_id' => '14', 'name' => 'San José del General'],
            ['state_id' => '3', 'city_id' => '14', 'name' => 'San Juan de Turbe'],

            ['state_id' => '3', 'city_id' => '15', 'name' => 'Cacique'],
            ['state_id' => '3', 'city_id' => '15', 'name' => 'Garrote'],
            ['state_id' => '3', 'city_id' => '15', 'name' => 'Isla Grande'],
            ['state_id' => '3', 'city_id' => '15', 'name' => 'María Chiquita'],
            ['state_id' => '3', 'city_id' => '15', 'name' => 'Portobelo'],

            ['state_id' => '3', 'city_id' => '16', 'name' => 'Cuango'],
            ['state_id' => '3', 'city_id' => '16', 'name' => 'Miramar'],
            ['state_id' => '3', 'city_id' => '16', 'name' => 'Nombre de Dios'],
            ['state_id' => '3', 'city_id' => '16', 'name' => 'Palenque'],
            ['state_id' => '3', 'city_id' => '16', 'name' => 'Palmira'],
            ['state_id' => '3', 'city_id' => '16', 'name' => 'Playa Chiquita'],
            ['state_id' => '3', 'city_id' => '16', 'name' => 'Santa Isabel'],
            ['state_id' => '3', 'city_id' => '16', 'name' => 'Viento Frío'],

            // Chiriquí

            ['state_id' => '4', 'city_id' => '17', 'name' => 'Alanje'],
            ['state_id' => '4', 'city_id' => '17', 'name' => 'Canta Gallo'],
            ['state_id' => '4', 'city_id' => '17', 'name' => 'Divalá'],
            ['state_id' => '4', 'city_id' => '17', 'name' => 'El Tejar'],
            ['state_id' => '4', 'city_id' => '17', 'name' => 'Guarumal'],
            ['state_id' => '4', 'city_id' => '17', 'name' => 'Nuevo México'],
            ['state_id' => '4', 'city_id' => '17', 'name' => 'Palo Grande'],
            ['state_id' => '4', 'city_id' => '17', 'name' => 'Querévalo'],
            ['state_id' => '4', 'city_id' => '17', 'name' => 'Santo Tomás'],

            ['state_id' => '4', 'city_id' => '18', 'name' => 'Baco'],
            ['state_id' => '4', 'city_id' => '18', 'name' => 'El Palmar'],
            ['state_id' => '4', 'city_id' => '18', 'name' => 'Limones'],
            ['state_id' => '4', 'city_id' => '18', 'name' => 'Manaca'],
            ['state_id' => '4', 'city_id' => '18', 'name' => 'Progreso'],
            ['state_id' => '4', 'city_id' => '18', 'name' => 'Puerto Armuelles'],
            ['state_id' => '4', 'city_id' => '18', 'name' => 'Rodolfo Aguilar Delgado'],

            ['state_id' => '4', 'city_id' => '19', 'name' => 'Bágala'],
            ['state_id' => '4', 'city_id' => '19', 'name' => 'Boquerón'],
            ['state_id' => '4', 'city_id' => '19', 'name' => 'Cordillera'],
            ['state_id' => '4', 'city_id' => '19', 'name' => 'Guabal'],
            ['state_id' => '4', 'city_id' => '19', 'name' => 'Guayabal'],
            ['state_id' => '4', 'city_id' => '19', 'name' => 'Paraíso'],
            ['state_id' => '4', 'city_id' => '19', 'name' => 'Pedregal'],
            ['state_id' => '4', 'city_id' => '19', 'name' => 'Tijeras'],

            ['state_id' => '4', 'city_id' => '20', 'name' => 'Alto Boquete'],
            ['state_id' => '4', 'city_id' => '20', 'name' => 'Bajo Boquete'],
            ['state_id' => '4', 'city_id' => '20', 'name' => 'Caldera'],
            ['state_id' => '4', 'city_id' => '20', 'name' => 'Jaramillo'],
            ['state_id' => '4', 'city_id' => '20', 'name' => 'Los Naranjos'],
            ['state_id' => '4', 'city_id' => '20', 'name' => 'Palmira'],

            ['state_id' => '4', 'city_id' => '21', 'name' => 'Aserrío de Gariché'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'Bugaba'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'El Bongo'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'Gómez'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'La Concepción'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'La Estrella'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'San Andrés'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'San Isidro'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'Santa Marta'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'Santa Rosa'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'Santo Domingo'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'Solano'],
            ['state_id' => '4', 'city_id' => '21', 'name' => 'Sortová'],

            ['state_id' => '4', 'city_id' => '22', 'name' => 'Bijagual'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'David'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'David Este'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'David Sur'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'Chiriquí'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'Cochea'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'Guacá'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'Las Lomas'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'Pedregal'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'San Carlos'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'San Pablo Nuevo'],
            ['state_id' => '4', 'city_id' => '22', 'name' => 'San Pablo Viejo'],

            ['state_id' => '4', 'city_id' => '23', 'name' => 'Dolega'],
            ['state_id' => '4', 'city_id' => '23', 'name' => 'Dos Ríos'],
            ['state_id' => '4', 'city_id' => '23', 'name' => 'Los Algarrobos'],
            ['state_id' => '4', 'city_id' => '23', 'name' => 'Los Anastacios'],
            ['state_id' => '4', 'city_id' => '23', 'name' => 'Potrerillos'],
            ['state_id' => '4', 'city_id' => '23', 'name' => 'Potrerillos Abajo'],
            ['state_id' => '4', 'city_id' => '23', 'name' => 'Rovira'],
            ['state_id' => '4', 'city_id' => '23', 'name' => 'Tinajas'],

            ['state_id' => '4', 'city_id' => '24', 'name' => 'Gualaca'],
            ['state_id' => '4', 'city_id' => '24', 'name' => 'Hornito'],
            ['state_id' => '4', 'city_id' => '24', 'name' => 'Los Ángeles'],
            ['state_id' => '4', 'city_id' => '24', 'name' => 'Paja de Sombrero'],
            ['state_id' => '4', 'city_id' => '24', 'name' => 'Rincón'],

            ['state_id' => '4', 'city_id' => '25', 'name' => 'El Nancito'],
            ['state_id' => '4', 'city_id' => '25', 'name' => 'El Porvenir'],
            ['state_id' => '4', 'city_id' => '25', 'name' => 'El Puerto'],
            ['state_id' => '4', 'city_id' => '25', 'name' => 'Remedios'],
            ['state_id' => '4', 'city_id' => '25', 'name' => 'Santa Lucía'],

            ['state_id' => '4', 'city_id' => '26', 'name' => 'Breñón'],
            ['state_id' => '4', 'city_id' => '26', 'name' => 'Cañas Gordas'],
            ['state_id' => '4', 'city_id' => '26', 'name' => 'Dominical'],
            ['state_id' => '4', 'city_id' => '26', 'name' => 'Monte Lirio'],
            ['state_id' => '4', 'city_id' => '26', 'name' => 'Plaza de Caisán'],
            ['state_id' => '4', 'city_id' => '26', 'name' => 'Río Sereno'],
            ['state_id' => '4', 'city_id' => '26', 'name' => 'Santa Clara'],
            ['state_id' => '4', 'city_id' => '26', 'name' => 'Santa Cruz'],

            ['state_id' => '4', 'city_id' => '27', 'name' => 'Juay'],
            ['state_id' => '4', 'city_id' => '27', 'name' => 'Lajas Adentro'],
            ['state_id' => '4', 'city_id' => '27', 'name' => 'Las Lajas'],
            ['state_id' => '4', 'city_id' => '27', 'name' => 'San Félix'],
            ['state_id' => '4', 'city_id' => '27', 'name' => 'Santa Cruz'],

            ['state_id' => '4', 'city_id' => '28', 'name' => 'Boca Chica'],
            ['state_id' => '4', 'city_id' => '28', 'name' => 'Boca del Monte'],
            ['state_id' => '4', 'city_id' => '28', 'name' => 'Horconcitos'],
            ['state_id' => '4', 'city_id' => '28', 'name' => 'San Juan'],
            ['state_id' => '4', 'city_id' => '28', 'name' => 'San Lorenzo'],

            ['state_id' => '4', 'city_id' => '29', 'name' => 'Cerro Punta'],
            ['state_id' => '4', 'city_id' => '29', 'name' => 'Cuesta de Piedra'],
            ['state_id' => '4', 'city_id' => '29', 'name' => 'Nueva California'],
            ['state_id' => '4', 'city_id' => '29', 'name' => 'Paso Ancho'],
            ['state_id' => '4', 'city_id' => '29', 'name' => 'Volcán'],

            ['state_id' => '4', 'city_id' => '30', 'name' => 'Bella Vista'],
            ['state_id' => '4', 'city_id' => '30', 'name' => 'Cerro Viejo'],
            ['state_id' => '4', 'city_id' => '30', 'name' => 'El Cristo'],
            ['state_id' => '4', 'city_id' => '30', 'name' => 'Justo Fidel Palacios'],
            ['state_id' => '4', 'city_id' => '30', 'name' => 'Lajas de Tolé'],
            ['state_id' => '4', 'city_id' => '30', 'name' => 'Potrero de Caña'],
            ['state_id' => '4', 'city_id' => '30', 'name' => 'Quebrada de Piedra'],
            ['state_id' => '4', 'city_id' => '30', 'name' => 'Tolé'],
            ['state_id' => '4', 'city_id' => '30', 'name' => 'Veladero'],

            // Darien

            ['state_id' => '5', 'city_id' => '31', 'name' => 'Camoganti'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'Chepigana'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'Garachiné'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'Jaqué'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'La Palma'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'Puerto Piña'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'Sambú'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'Setegantí'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'Taimatí'],
            ['state_id' => '5', 'city_id' => '31', 'name' => 'Tucutí'],

            ['state_id' => '5', 'city_id' => '32', 'name' => 'Boca de Cupe'],
            ['state_id' => '5', 'city_id' => '32', 'name' => 'El Real de Santa María'],
            ['state_id' => '5', 'city_id' => '32', 'name' => 'Metetí'],
            ['state_id' => '5', 'city_id' => '32', 'name' => 'Paya'],
            ['state_id' => '5', 'city_id' => '32', 'name' => 'Pinogana'],
            ['state_id' => '5', 'city_id' => '32', 'name' => 'Púcuro'],
            ['state_id' => '5', 'city_id' => '32', 'name' => 'Yape'],
            ['state_id' => '5', 'city_id' => '32', 'name' => 'Yaviza'],
            ['state_id' => '5', 'city_id' => '32', 'name' => 'Wargandí'],

            ['state_id' => '5', 'city_id' => '33', 'name' => 'Agua Fría'],
            ['state_id' => '5', 'city_id' => '33', 'name' => 'Cucunatí'],
            ['state_id' => '5', 'city_id' => '33', 'name' => 'Río Iglesias'],
            ['state_id' => '5', 'city_id' => '33', 'name' => 'Río Congo'],
            ['state_id' => '5', 'city_id' => '33', 'name' => 'Río Congo Arriba'],
            ['state_id' => '5', 'city_id' => '33', 'name' => 'Santa Fe'],
            ['state_id' => '5', 'city_id' => '33', 'name' => 'Zapallal'],

            // Chitré

            ['state_id' => '6', 'city_id' => '34', 'name' => 'Chitré'],
            ['state_id' => '6', 'city_id' => '34', 'name' => 'La Arena'],
            ['state_id' => '6', 'city_id' => '34', 'name' => 'Llano Bonito'],
            ['state_id' => '6', 'city_id' => '34', 'name' => 'San Juan Bautista'],
            ['state_id' => '6', 'city_id' => '34', 'name' => 'San Miguel de Monagrillo'],

            ['state_id' => '6', 'city_id' => '35', 'name' => 'Chepo'],
            ['state_id' => '6', 'city_id' => '35', 'name' => 'Chumical'],
            ['state_id' => '6', 'city_id' => '35', 'name' => 'El Toro'],
            ['state_id' => '6', 'city_id' => '35', 'name' => 'Las Minas'],
            ['state_id' => '6', 'city_id' => '35', 'name' => 'Leones'],
            ['state_id' => '6', 'city_id' => '35', 'name' => 'Quebrada del Rosario'],
            ['state_id' => '6', 'city_id' => '35', 'name' => 'Quebrada El Ciprián'],

            ['state_id' => '6', 'city_id' => '36', 'name' => 'El Calabacito'],
            ['state_id' => '6', 'city_id' => '36', 'name' => 'El Capurí'],
            ['state_id' => '6', 'city_id' => '36', 'name' => 'El Cedro'],
            ['state_id' => '6', 'city_id' => '36', 'name' => 'La Arena'],
            ['state_id' => '6', 'city_id' => '36', 'name' => 'La Pitaloza'],
            ['state_id' => '6', 'city_id' => '36', 'name' => 'Las Llanas'],
            ['state_id' => '6', 'city_id' => '36', 'name' => 'Los Cerritos'],
            ['state_id' => '6', 'city_id' => '36', 'name' => 'Los Cerros de Paja'],
            ['state_id' => '6', 'city_id' => '36', 'name' => 'Los Pozos'],

            ['state_id' => '6', 'city_id' => '37', 'name' => 'Cerro Largo'],
            ['state_id' => '6', 'city_id' => '37', 'name' => 'El Tijera'],
            ['state_id' => '6', 'city_id' => '37', 'name' => 'Entradero del Castillo'],
            ['state_id' => '6', 'city_id' => '37', 'name' => 'Llano Grande'],
            ['state_id' => '6', 'city_id' => '37', 'name' => 'Los Llanos'],
            ['state_id' => '6', 'city_id' => '37', 'name' => 'Menchaca'],
            ['state_id' => '6', 'city_id' => '37', 'name' => 'Peñas Chatas'],
            ['state_id' => '6', 'city_id' => '37', 'name' => 'San Sebastián de Ocú'],

            ['state_id' => '6', 'city_id' => '38', 'name' => 'Cabuya'],
            ['state_id' => '6', 'city_id' => '38', 'name' => 'Llano de la Cruz'],
            ['state_id' => '6', 'city_id' => '38', 'name' => 'Los Castillos'],
            ['state_id' => '6', 'city_id' => '38', 'name' => 'París'],
            ['state_id' => '6', 'city_id' => '38', 'name' => 'Parita'],
            ['state_id' => '6', 'city_id' => '38', 'name' => 'Portobelillo'],
            ['state_id' => '6', 'city_id' => '38', 'name' => 'Potuga'],

            ['state_id' => '6', 'city_id' => '39', 'name' => 'El Barrero'],
            ['state_id' => '6', 'city_id' => '39', 'name' => 'El Ciruelo'],
            ['state_id' => '6', 'city_id' => '39', 'name' => 'El Pájaro'],
            ['state_id' => '6', 'city_id' => '39', 'name' => 'El Pedregoso'],
            ['state_id' => '6', 'city_id' => '39', 'name' => 'Las Cabras'],
            ['state_id' => '6', 'city_id' => '39', 'name' => 'Pesé'],
            ['state_id' => '6', 'city_id' => '39', 'name' => 'Rincón Hondo'],
            ['state_id' => '6', 'city_id' => '39', 'name' => 'Sabanagrande'],

            ['state_id' => '6', 'city_id' => '40', 'name' => 'Chupampa'],
            ['state_id' => '6', 'city_id' => '40', 'name' => 'El Limón'],
            ['state_id' => '6', 'city_id' => '40', 'name' => 'El Rincón'],
            ['state_id' => '6', 'city_id' => '40', 'name' => 'Los Canelos'],
            ['state_id' => '6', 'city_id' => '40', 'name' => 'Santa María'],

            // Los Santos

            ['state_id' => '7', 'city_id' => '41', 'name' => 'El Espinal'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'El Hato'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'El Macano'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'Guararé'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'Guararé Arriba'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'La Enea'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'La Pasera'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'Las Trancas'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'Llano Abajo'],
            ['state_id' => '7', 'city_id' => '41', 'name' => 'Perales'],

            ['state_id' => '7', 'city_id' => '42', 'name' => 'Bajo Corral'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Bayano'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'El Carate'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'El Cocal'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'El Manantial'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'El Muñoz'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'El Pedregoso'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'El Sesteadero'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'La Laja'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'La Miel'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'La Palma'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'La Tiza'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Las Palmitas'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Las Tablas'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Las Tablas Abajo'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Nuario'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Palmira'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Peña Blanca'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Río Hondo'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'San José'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'San Miguel'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Santo Domingo'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Valle Rico'],
            ['state_id' => '7', 'city_id' => '42', 'name' => 'Vallerriquito'],

            ['state_id' => '7', 'city_id' => '43', 'name' => 'Agua Buena'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'El Ejido'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'El Guásimo'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'La Colorada'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'La Espigadilla'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'La Villa de Los Santos'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Las Cruces'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Las Guabas'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Los Ángeles'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Los Olivos'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Llano Largo'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Sabanagrande'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Santa Ana'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Tres Quebradas'],
            ['state_id' => '7', 'city_id' => '43', 'name' => 'Villa Lourdes'],

            ['state_id' => '7', 'city_id' => '44', 'name' => 'Bahía Honda'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'Bajos de Güera'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'Chupá'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'Corozal'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'El Cedro'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'Espino Amarillo'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'La Mesa'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'Las Palmas'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'Llano de Piedras'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'Macaracas'],
            ['state_id' => '7', 'city_id' => '44', 'name' => 'Mogollón'],

            ['state_id' => '7', 'city_id' => '45', 'name' => 'Los Asientos'],
            ['state_id' => '7', 'city_id' => '45', 'name' => 'Mariabé'],
            ['state_id' => '7', 'city_id' => '45', 'name' => 'Oria Arriba'],
            ['state_id' => '7', 'city_id' => '45', 'name' => 'Pedasí'],
            ['state_id' => '7', 'city_id' => '45', 'name' => 'Purio'],

            ['state_id' => '7', 'city_id' => '46', 'name' => 'El Cañafístulo'],
            ['state_id' => '7', 'city_id' => '46', 'name' => 'Lajamina'],
            ['state_id' => '7', 'city_id' => '46', 'name' => 'Paraíso'],
            ['state_id' => '7', 'city_id' => '46', 'name' => 'Paritilla'],
            ['state_id' => '7', 'city_id' => '46', 'name' => 'Pocrí'],

            ['state_id' => '7', 'city_id' => '47', 'name' => 'Altos de Güera'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'Cambutal'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'Cañas'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'El Bebedero'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'El Cacao'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'El Cortezo'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'Flores'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'Guánico'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'Isla de Cañas'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'La Tronosa'],
            ['state_id' => '7', 'city_id' => '47', 'name' => 'Tonosí'],

            // Panamá

            ['state_id' => '8', 'city_id' => '48', 'name' => 'La Guinea'],
            ['state_id' => '8', 'city_id' => '48', 'name' => 'La Ensenada'],
            ['state_id' => '8', 'city_id' => '48', 'name' => 'La Esmeralda'],
            ['state_id' => '8', 'city_id' => '48', 'name' => 'Pedro González'],
            ['state_id' => '8', 'city_id' => '48', 'name' => 'Saboga'],
            ['state_id' => '8', 'city_id' => '48', 'name' => 'San Miguel'],

            ['state_id' => '8', 'city_id' => '49', 'name' => 'Cañita'],
            ['state_id' => '8', 'city_id' => '49', 'name' => 'Chepillo'],
            ['state_id' => '8', 'city_id' => '49', 'name' => 'Chepo'],
            ['state_id' => '8', 'city_id' => '49', 'name' => 'El Llano'],
            ['state_id' => '8', 'city_id' => '49', 'name' => 'Las Margaritas'],
            ['state_id' => '8', 'city_id' => '49', 'name' => 'Madugandí'],
            ['state_id' => '8', 'city_id' => '49', 'name' => 'Santa Cruz de Chinina'],
            ['state_id' => '8', 'city_id' => '49', 'name' => 'Tortí'],

            ['state_id' => '8', 'city_id' => '50', 'name' => 'Brujas'],
            ['state_id' => '8', 'city_id' => '50', 'name' => 'Chimán'],
            ['state_id' => '8', 'city_id' => '50', 'name' => 'Gonzalo Vásquez'],
            ['state_id' => '8', 'city_id' => '50', 'name' => 'Pásiga'],
            ['state_id' => '8', 'city_id' => '50', 'name' => 'Unión Santeña'],

            ['state_id' => '8', 'city_id' => '51', 'name' => '24 de Diciembre'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Alcalde Díaz'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Ancón'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Bella Vista'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Betania'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Caimitillo'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Calidonia'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Chilibre'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Curundú'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Don Bosco'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'El Chorrillo'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Ernesto Córdoba Campos'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Juan Díaz'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Las Cumbres'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Las Garzas'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Las Mañanitas'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Pacora'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Parque Lefevre'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Pedregal'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Pueblo Nuevo'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Río Abajo'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'San Felipe'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'San Francisco'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'San Martín'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Santa Ana'],
            ['state_id' => '8', 'city_id' => '51', 'name' => 'Tocumen'],

            ['state_id' => '8', 'city_id' => '52', 'name' => 'Amelia Denis De Icaza'],
            ['state_id' => '8', 'city_id' => '52', 'name' => 'Arnulfo Arias'],
            ['state_id' => '8', 'city_id' => '52', 'name' => 'Belisario Frías'],
            ['state_id' => '8', 'city_id' => '52', 'name' => 'Belisario Porras'],
            ['state_id' => '8', 'city_id' => '52', 'name' => 'José Domingo Espinar'],
            ['state_id' => '8', 'city_id' => '52', 'name' => 'Mateo Iturralde'],
            ['state_id' => '8', 'city_id' => '52', 'name' => 'Omar Torrijos'],
            ['state_id' => '8', 'city_id' => '52', 'name' => 'Rufina Alfaro'],
            ['state_id' => '8', 'city_id' => '52', 'name' => 'Victoriano Lorenzo'],

            ['state_id' => '8', 'city_id' => '53', 'name' => 'Otoque Occidente'],
            ['state_id' => '8', 'city_id' => '53', 'name' => 'Otoque Oriente'],
            ['state_id' => '8', 'city_id' => '53', 'name' => 'Taboga'],

            // Veraguas

            ['state_id' => '9', 'city_id' => '54', 'name' => 'Atalaya'],
            ['state_id' => '9', 'city_id' => '54', 'name' => 'El Barrito'],
            ['state_id' => '9', 'city_id' => '54', 'name' => 'La Carrillo'],
            ['state_id' => '9', 'city_id' => '54', 'name' => 'La Montañuela'],
            ['state_id' => '9', 'city_id' => '54', 'name' => 'San Antonio'],

            ['state_id' => '9', 'city_id' => '55', 'name' => 'Barnizal'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'Calobre'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'Chitra'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'El Cocla'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'El Potrero'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'La Laguna'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'La Raya de Calobre'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'La Tetilla'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'La Yeguada'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'Las Guías'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'Monjarás'],
            ['state_id' => '9', 'city_id' => '55', 'name' => 'San José'],

            ['state_id' => '9', 'city_id' => '56', 'name' => 'Cañazas'],
            ['state_id' => '9', 'city_id' => '56', 'name' => 'Cerro de Plata'],
            ['state_id' => '9', 'city_id' => '56', 'name' => 'El Aromillo'],
            ['state_id' => '9', 'city_id' => '56', 'name' => 'El Picador'],
            ['state_id' => '9', 'city_id' => '56', 'name' => 'Las Cruces'],
            ['state_id' => '9', 'city_id' => '56', 'name' => 'Los Valles'],
            ['state_id' => '9', 'city_id' => '56', 'name' => 'San José'],
            ['state_id' => '9', 'city_id' => '56', 'name' => 'San Marcelo'],

            ['state_id' => '9', 'city_id' => '57', 'name' => 'Bisvalles'],
            ['state_id' => '9', 'city_id' => '57', 'name' => 'Boró'],
            ['state_id' => '9', 'city_id' => '57', 'name' => 'El Higo'],
            ['state_id' => '9', 'city_id' => '57', 'name' => 'La Mesa'],
            ['state_id' => '9', 'city_id' => '57', 'name' => 'Llano Grande'],
            ['state_id' => '9', 'city_id' => '57', 'name' => 'Los Milagros'],
            ['state_id' => '9', 'city_id' => '57', 'name' => 'San Bartolo'],

            ['state_id' => '9', 'city_id' => '58', 'name' => 'Cerro de Casa'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'Corozal'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'El María'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'El Prado'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'El Rincón'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'Las Palmas'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'Lolá'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'Manuel E. Amador Terrero'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'Pixvae'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'Puerto Vidal'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'San Martín de Porres'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'Viguí'],
            ['state_id' => '9', 'city_id' => '58', 'name' => 'Zapotillo'],

            ['state_id' => '9', 'city_id' => '59', 'name' => 'Arenas'],
            ['state_id' => '9', 'city_id' => '59', 'name' => 'El Cacao'],
            ['state_id' => '9', 'city_id' => '59', 'name' => 'Mariato'],
            ['state_id' => '9', 'city_id' => '59', 'name' => 'Quebro'],
            ['state_id' => '9', 'city_id' => '59', 'name' => 'Tebario'],

            ['state_id' => '9', 'city_id' => '60', 'name' => 'Cébaco'],
            ['state_id' => '9', 'city_id' => '60', 'name' => 'Costa Hermosa'],
            ['state_id' => '9', 'city_id' => '60', 'name' => 'Gobernadora'],
            ['state_id' => '9', 'city_id' => '60', 'name' => 'La Garceana'],
            ['state_id' => '9', 'city_id' => '60', 'name' => 'Leones'],
            ['state_id' => '9', 'city_id' => '60', 'name' => 'Montijo'],
            ['state_id' => '9', 'city_id' => '60', 'name' => 'Pilón'],
            ['state_id' => '9', 'city_id' => '60', 'name' => 'Unión del Norte'],

            ['state_id' => '9', 'city_id' => '61', 'name' => 'Catorce de Noviembre'],
            ['state_id' => '9', 'city_id' => '61', 'name' => 'Las Huacas'],
            ['state_id' => '9', 'city_id' => '61', 'name' => 'Los Castillos'],
            ['state_id' => '9', 'city_id' => '61', 'name' => 'Río de Jesús'],
            ['state_id' => '9', 'city_id' => '61', 'name' => 'Utira'],

            ['state_id' => '9', 'city_id' => '62', 'name' => 'Corral Falso'],
            ['state_id' => '9', 'city_id' => '62', 'name' => 'Los Hatillos'],
            ['state_id' => '9', 'city_id' => '62', 'name' => 'Remance'],
            ['state_id' => '9', 'city_id' => '62', 'name' => 'San Francisco'],
            ['state_id' => '9', 'city_id' => '62', 'name' => 'San Juan'],
            ['state_id' => '9', 'city_id' => '62', 'name' => 'San José'],

            ['state_id' => '9', 'city_id' => '63', 'name' => 'Calovébora'],
            ['state_id' => '9', 'city_id' => '63', 'name' => 'El Alto'],
            ['state_id' => '9', 'city_id' => '63', 'name' => 'El Cuay'],
            ['state_id' => '9', 'city_id' => '63', 'name' => 'El Pantano'],
            ['state_id' => '9', 'city_id' => '63', 'name' => 'Gatuncito'],
            ['state_id' => '9', 'city_id' => '63', 'name' => 'Río Luis'],
            ['state_id' => '9', 'city_id' => '63', 'name' => 'Rubén Cantú'],
            ['state_id' => '9', 'city_id' => '63', 'name' => 'Santa Fe'],

            ['state_id' => '9', 'city_id' => '64', 'name' => 'Canto del Llano'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Carlos Santana Ávila'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Edwin Fábrega'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'La Colorada'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'La Peña'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'La Raya de Santa María'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Los Algarrobos'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Nuevo Santiago'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Ponuga'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Rodrigo Luque'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'San Martín de Porres'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'San Pedro del Espino'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Santiago'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Santiago Este'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Santiago Sur'],
            ['state_id' => '9', 'city_id' => '64', 'name' => 'Urracá'],

            ['state_id' => '9', 'city_id' => '65', 'name' => 'Bahía Honda'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'Calidonia'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'Cativé'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'El Marañón'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'Guarumal'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'Hicaco'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'La Soledad'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'La Trinchera'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'Quebrada de Oro'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'Río Grande'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'Rodeo Viejo'],
            ['state_id' => '9', 'city_id' => '65', 'name' => 'Soná'],

            // Comarca Guna Yala

            ['state_id' => '10', 'city_id' => '66', 'name' => 'Ailigandí'],
            ['state_id' => '10', 'city_id' => '66', 'name' => 'Narganá'],
            ['state_id' => '10', 'city_id' => '66', 'name' => 'Puerto Obaldía'],
            ['state_id' => '10', 'city_id' => '66', 'name' => 'Tubuala'],

            // Comarca Emberá-Wounaan

            ['state_id' => '10', 'city_id' => '67', 'name' => 'Cirilo Guaynora'],
            ['state_id' => '10', 'city_id' => '67', 'name' => 'Lajas Blancas'],
            ['state_id' => '10', 'city_id' => '67', 'name' => 'Manuel Ortega'],

            ['state_id' => '10', 'city_id' => '68', 'name' => 'Jingurundó'],
            ['state_id' => '10', 'city_id' => '68', 'name' => 'Río Sabalo'],

            // Comarca Ngäbe-Buglé

            ['state_id' => '10', 'city_id' => '69', 'name' => 'Bürüöte Käbitini'],
            ['state_id' => '10', 'city_id' => '69', 'name' => 'Blamtdi'],
            ['state_id' => '10', 'city_id' => '69', 'name' => 'Jebaygätde'],
            ['state_id' => '10', 'city_id' => '69', 'name' => 'Kruningäde'],
            ['state_id' => '10', 'city_id' => '69', 'name' => 'Krua'],
            ['state_id' => '10', 'city_id' => '69', 'name' => 'Nämnoní'],
            ['state_id' => '10', 'city_id' => '69', 'name' => 'Niba'],
            ['state_id' => '10', 'city_id' => '69', 'name' => 'Nwanabäda'],

            ['state_id' => '10', 'city_id' => '70', 'name' => 'Burí'],
            ['state_id' => '10', 'city_id' => '70', 'name' => 'Guariviara'],
            ['state_id' => '10', 'city_id' => '70', 'name' => 'Man Creek'],
            ['state_id' => '10', 'city_id' => '70', 'name' => 'Samboa'],
            ['state_id' => '10', 'city_id' => '70', 'name' => 'Tu Gwai'],

            ['state_id' => '10', 'city_id' => '71', 'name' => 'Bisiragätde'],
            ['state_id' => '10', 'city_id' => '71', 'name' => 'Calante'],
            ['state_id' => '10', 'city_id' => '71', 'name' => 'Gwaranibotdä'],
            ['state_id' => '10', 'city_id' => '71', 'name' => 'Jätainde'],
            ['state_id' => '10', 'city_id' => '71', 'name' => 'Kankintubotdä'],
            ['state_id' => '10', 'city_id' => '71', 'name' => 'Mününigätde'],
            ['state_id' => '10', 'city_id' => '71', 'name' => 'Ñö Tolentde'],

            ['state_id' => '10', 'city_id' => '72', 'name' => 'Dririkötde'],
            ['state_id' => '10', 'city_id' => '72', 'name' => 'Konurebätdä'],
            ['state_id' => '10', 'city_id' => '72', 'name' => 'Muina'],
            ['state_id' => '10', 'city_id' => '72', 'name' => 'Orikötde'],
            ['state_id' => '10', 'city_id' => '72', 'name' => 'Saborikötde'],

            ['state_id' => '10', 'city_id' => '73', 'name' => 'Hato Culantro'],
            ['state_id' => '10', 'city_id' => '73', 'name' => 'Jlugribotdó'],
            ['state_id' => '10', 'city_id' => '73', 'name' => 'Jonondi'],
            ['state_id' => '10', 'city_id' => '73', 'name' => 'Kaninbotdä'],
            ['state_id' => '10', 'city_id' => '73', 'name' => 'Krudugrade'],
            ['state_id' => '10', 'city_id' => '73', 'name' => 'Orerigidetde'],
            ['state_id' => '10', 'city_id' => '73', 'name' => 'Salto Dupí'],
            ['state_id' => '10', 'city_id' => '73', 'name' => 'Tónonbitdi'],

            ['state_id' => '10', 'city_id' => '74', 'name' => 'Bakama'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Cerro Caña'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Cerro Puerco'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Dikeri'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Kikari'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Kikintani'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Krüa'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Mreeni'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Munängätäte'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Nibra'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Röka'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Siädogwäbitdi'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Sitio Prado'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Tonbti'],
            ['state_id' => '10', 'city_id' => '74', 'name' => 'Umaní, Diko'],

            ['state_id' => '10', 'city_id' => '75', 'name' => 'Bagaibotdä'],
            ['state_id' => '10', 'city_id' => '75', 'name' => 'Cerro Iglesias'],
            ['state_id' => '10', 'city_id' => '75', 'name' => 'Jädeberi'],
            ['state_id' => '10', 'city_id' => '75', 'name' => 'Susama'],
            ['state_id' => '10', 'city_id' => '75', 'name' => 'Unbitdi'],

            ['state_id' => '10', 'city_id' => '76', 'name' => 'Agua de Salud'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'Buenos Aires'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'Guayabito'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'Güibale'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'Jukri'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'El Bale'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'El Paredón'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'El Peñón'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'Muakwata Kubu'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'Muakwatabti'],
            ['state_id' => '10', 'city_id' => '76', 'name' => 'Ngöbö Kiabti'],

            ['state_id' => '10', 'city_id' => '77', 'name' => 'Bledeshia'],
            ['state_id' => '10', 'city_id' => '77', 'name' => 'Dogata'],
            ['state_id' => '10', 'city_id' => '77', 'name' => 'Gdogüeshia'],
            ['state_id' => '10', 'city_id' => '77', 'name' => 'Ijuicho'],
            ['state_id' => '10', 'city_id' => '77', 'name' => 'Jiküi'],

            // Panamá Oeste

            ['state_id' => '10', 'city_id' => '78', 'name' => 'Arraiján'],
            ['state_id' => '10', 'city_id' => '78', 'name' => 'Burunga'],
            ['state_id' => '10', 'city_id' => '78', 'name' => 'Cerro Silvestre'],
            ['state_id' => '10', 'city_id' => '78', 'name' => 'Juan Demóstenes Arosemena'],
            ['state_id' => '10', 'city_id' => '78', 'name' => 'Nuevo Emperador'],
            ['state_id' => '10', 'city_id' => '78', 'name' => 'Santa Clara'],
            ['state_id' => '10', 'city_id' => '78', 'name' => 'Vacamonte'],
            ['state_id' => '10', 'city_id' => '78', 'name' => 'Veracruz'],
            ['state_id' => '10', 'city_id' => '78', 'name' => 'Vista Alegre'],

            ['state_id' => '10', 'city_id' => '79', 'name' => 'Caimito'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Campana'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Capira'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Cermeño'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Cirí de Los Sotos'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Cirí Grande'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'El Cacao'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'La Trinidad'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Las Ollas Arriba'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Lídice'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Santa Rosa'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Villa Carmen'],
            ['state_id' => '10', 'city_id' => '79', 'name' => 'Villa Rosario'],

            ['state_id' => '10', 'city_id' => '80', 'name' => 'Bejuco'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'Buenos Aires'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'Cabuya, Chicá'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'Chame'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'El Líbano'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'Las Lajas'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'Nueva Gorgona'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'Punta Chame'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'Sajalices'],
            ['state_id' => '10', 'city_id' => '80', 'name' => 'Sorá'],

            ['state_id' => '10', 'city_id' => '81', 'name' => 'Amador'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Arosemena'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Barrio Balboa'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Barrio Colón'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'El Arado'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'El Coco'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Feuillet'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Guadalupe'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Herrera'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Hurtado'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Iturralde'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'La Represa'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Los Díaz'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Mendoza'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Obaldía'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Playa Leona'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Puerto Caimito'],
            ['state_id' => '10', 'city_id' => '81', 'name' => 'Santa Rita'],

            ['state_id' => '10', 'city_id' => '82', 'name' => 'El Espino'],
            ['state_id' => '10', 'city_id' => '82', 'name' => 'El Higo'],
            ['state_id' => '10', 'city_id' => '82', 'name' => 'Guayabito'],
            ['state_id' => '10', 'city_id' => '82', 'name' => 'La Ermita'],
            ['state_id' => '10', 'city_id' => '82', 'name' => 'La Laguna'],
            ['state_id' => '10', 'city_id' => '82', 'name' => 'Las Uvas'],
            ['state_id' => '10', 'city_id' => '82', 'name' => 'Los Llanitos'],
            ['state_id' => '10', 'city_id' => '82', 'name' => 'San Carlos'],
            ['state_id' => '10', 'city_id' => '82', 'name' => 'San José'],

            // Comarca Naso Tjër Di

            ['state_id' => '10', 'city_id' => '83', 'name' => 'Teribe'],
            ['state_id' => '10', 'city_id' => '83', 'name' => 'San San Drui'],
            ['state_id' => '10', 'city_id' => '83', 'name' => 'Bonyik']
        ]);
    }
}
